
##################################################################################################
# details service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-app-deploy
  labels:
    app: details-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  details-app
  template:
    metadata:
      labels:
        app:  details-app
    spec:
      containers:
        - name: details-app
          image: yuyatinnefeld/microservice-details-app:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: details-service
spec:
  selector:
    app:  details-app
  ports:
    - port: 7777
      targetPort: 7777
      name: http-details
  type: ClusterIP