##################################################################################################
# payment service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deploy
  labels:
    app: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-app
  template:
    metadata:
      labels:
        app:  payment-app
    spec:
      containers:
        - name: payment-app
          image: yuyatinnefeld/microservice-payment-app:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app:  payment-app
  ports:
    - port: 8888
      targetPort: 8888
      name: http-payment
  type: ClusterIP
