stages:
  - build

build_image:
  stage: build
  image: docker
  services:
    - name: docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd $WORKING_DIR
  script:
    - docker build -t $CI_REGISTRY/$GITLAB_GROUP_ID/$GITLAB_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
    - docker push $CI_REGISTRY/$GITLAB_GROUP_ID/$GITLAB_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
  variables:
    WORKING_DIR: app/details
    GITLAB_GROUP_ID: "k8s1940325"
    GITLAB_PROJECT_ID: "k8s-microservices"
    IMAGE_NAME: "microservice-details-app"
    IMAGE_TAG: "1.0.0"

