stages:
  - build

build_image:
  stage: build
  image: docker
  services:
    - name: docker:dind
  script:
    - docker ps
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #- docker build -t $CI_REGISTRY/group/project/image:latest .
    #- docker push $CI_REGISTRY/group/project/image:latest