##################################################################################################
# payment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment
    service: payment
spec:
  selector:
    app:  payment-app
  ports:
    - port: 8888
      targetPort: 8888
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
---
#################################################################################################
# deployment v1
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-app
      version: v1
  template:
    metadata:
      labels:
        app:  payment-app
        version: v1
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: payment-app
          image: yuyatinnefeld/microservice-payment-app:1.0.0
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "1.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#################################################################################################
# deployment v2
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v2
  labels:
    app: payment-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-app
      version: v2
  template:
    metadata:
      labels:
        app:  payment-app
        version: v2
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: payment-app
          image: yuyatinnefeld/microservice-payment-app:2.0.0
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "2.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#################################################################################################
# deployment v3
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v3
  labels:
    app: payment-app
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-app
      version: v3
  template:
    metadata:
      labels:
        app:  payment-app
        version: v3
    spec:
      serviceAccountName: payment-sa
      containers:
        - name: payment-app
          image: yuyatinnefeld/microservice-payment-app:3.0.0
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "3.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name