#################################################################################################
# reviews
#################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  labels:
    app: reviews
    service: reviews
spec:
  selector:
    app:  reviews-app
  ports:
    - port: 9999
      targetPort: 9999
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reviews-sa
---
#################################################################################################
# deployment v1
#################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: reviews-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  reviews-app
      version: v1
  template:
    metadata:
      name: reviews
      labels:
        app:  reviews-app
        version: v1
    spec:
      serviceAccountName: reviews-sa
      containers:
        - name: reviews-app
          image: yuyatinnefeld/microservice-reviews-app:1.0.0
          ports:
            - containerPort: 9999
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "1.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#################################################################################################
# deployment v2
#################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: reviews-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  reviews-app
      version: v2
  template:
    metadata:
      name: reviews
      labels:
        app:  reviews-app
        version: v2
    spec:
      serviceAccountName: reviews-sa
      containers:
        - name: reviews-app
          image: yuyatinnefeld/microservice-reviews-app:2.0.0
          ports:
            - containerPort: 9999
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "2.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#################################################################################################
# deployment v3
#################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: reviews-app
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  reviews-app
      version: v3
  template:
    metadata:
      name: reviews
      labels:
        app:  reviews-app
        version: v3
    spec:
      serviceAccountName: reviews-sa
      containers:
        - name: reviews-app
          image: yuyatinnefeld/microservice-reviews-app:3.0.0
          ports:
            - containerPort: 9999
          env:
            - name: MESSAGE
              value: "MY_K8S_MESSAGE"
            - name: VERSION
              value: "3.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name