##################################################################################################
# reviews service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-app-deploy
  labels:
    app: reviews-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  reviews-app
  template:
    metadata:
      labels:
        app:  reviews-app
    spec:
      containers:
        - name: reviews-app
          image: yuyatinnefeld/microservice-reviews-app:2.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app:  reviews-app
  ports:
    - port: 9999
      targetPort: 9999
      name: http-reviews
  type: ClusterIP