
##################################################################################################
# details service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-app-deploy
  labels:
    app: details-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  details-app
  template:
    metadata:
      labels:
        app:  details-app
    spec:
      containers:
        - name: details-app
          image: yuyatinnefeld/microservice-details-app:3.0.0
          ports:
            - containerPort: 7777
          env:
            - name: MESSAGE
              value: "..."
            - name: VERSION
              value: "3.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: details-service
spec:
  selector:
    app:  details-app
  ports:
    - port: 7777
      targetPort: 7777
      name: http-details
  type: ClusterIP