##################################################################################################
# payment service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deploy
  labels:
    app: payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment-app
  template:
    metadata:
      labels:
        app:  payment-app
    spec:
      containers:
        - name: payment-app
          image: yuyatinnefeld/microservice-payment-app:3.0.0
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "U_U"
            - name: VERSION
              value: "3.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app:  payment-app
  ports:
    - port: 8888
      targetPort: 8888
      name: http-payment
  type: ClusterIP
