##################################################################################################
# reviews service
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-app-deploy
  labels:
    app: reviews-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  reviews-app
  template:
    metadata:
      labels:
        app:  reviews-app
    spec:
      containers:
        - name: reviews-app
          image: yuyatinnefeld/microservice-reviews-app:3.0.0
          ports:
            - containerPort: 8888
          env:
            - name: MESSAGE
              value: "..."
            - name: VERSION
              value: "3.0.0"
            - name: ENV
              value: "DEV"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app:  reviews-app
  ports:
    - port: 9999
      targetPort: 9999
      name: http-reviews
  type: ClusterIP