##################################################################################################
# fronend service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: {{ .Values.frontend.appName }}
    service: {{ .Values.frontend.serviceName }}
spec:
  selector:
    app:  {{ .Values.frontend.appName }}
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: {{ .Values.frontend.appName }}
    service: frontend
    version: v1
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
        version: v1
    spec:
      serviceAccountName: {{ .Values.frontend.serviceAccountName }}
      containers:
        - name: {{ .Values.frontend.appName }}
          image: "{{ .Values.frontend.imageName }}:1.0.0"