##################################################################################################
# reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.reviews.serviceName }}
  labels:
    app: {{ .Values.reviews.appName }}
    service: {{ .Values.reviews.serviceName }}
spec:
  selector:
    app:  {{ .Values.reviews.appName }}
  ports:
    - port: 9999
      targetPort: 9999
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.reviews.serviceAccountName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v1
  labels:
    app: {{ .Values.reviews.appName }}
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.reviews.appName }}
      version: v1
  template:
    metadata:
      name: reviews
      labels:
        app:  {{ .Values.reviews.appName }}
        version: v1
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccountName }}
      containers:
        - name: {{ .Values.reviews.appName }}
          image: "{{ .Values.reviews.imageName }}:1.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
  labels:
    app: {{ .Values.reviews.appName }}
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.reviews.appName }}
      version: v2
  template:
    metadata:
      name: reviews
      labels:
        app:  {{ .Values.reviews.appName }}
        version: v2
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccountName }}
      containers:
        - name: {{ .Values.reviews.appName }}
          image: "{{ .Values.reviews.imageName }}:2.0.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v3
  labels:
    app: {{ .Values.reviews.appName }}
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ .Values.reviews.appName }}
      version: v3
  template:
    metadata:
      name: reviews
      labels:
        app:  {{ .Values.reviews.appName }}
        version: v3
    spec:
      serviceAccountName: {{ .Values.reviews.serviceAccountName }}
      containers:
        - name: {{ .Values.reviews.appName }}
          image: "{{ .Values.reviews.imageName }}:3.0.0"